Repository Nothooon/Brott, pull requests merged in 2023-10, with the labels that each got.

#7 #5 Moving random choices to config + more answer depth
  bot.py
  config/config.json
  features/feur.py
  ressources/images/FeurAllezHopLa.png
Labels: enhancement

#10 Update libs to patch aiohttp vulnerability
  poetry.lock
Labels: to_master, patch_vulnerability

#13 Logs
  .gitignore
  bot.py
  features/feurlog.csv
Labels: feature

#16 Moving logging to its own file
  .gitignore
  bot.py
  config/config.json
  data/feurlog.csv
  features/feurlog.csv
  features/logging.py
Labels: enhancement, to_master
